### ISSUE TITLE
Data Cleaning

### ISSUE THREAD

**Issue by annychih** [UBC-MDS/DSCI_522_Group304#16]
List of things we still need to do for data cleaning (based on group meeting):

1. Change the school year to a numeric column based on the year the school year began in (ex. change 2007/08 to 2007). We'll need this to make the scatterplots.

2. Figure out why the Scores are not being read in correctly (ex. the maximum score shown in R is NOT the actual maximum and it's messing up the summary data).

**Comment by zouwenjiao** [comment]
After change the load path, the SCORE column is correct now.

**Comment by annychih** [comment]
The clean_data.py script changes the school year to a numeric column and splits it into year_start and year_end.
