### ISSUE TITLE
Milestone 1: Code of Conduct File

### ISSUE THREAD

**Issue by annychih** [UBC-MDS/DSCI_522_Group304#2]
Need to make a Code of Conduct file and save it to the root of the GitHub.com project repo

From Milestone 1: 
At minimum, we believe that a good/effective code of conduct should include:

- A Statement on diversity and inclusivity
- Details on expected, and unacceptable behaviour
- A list of consequences for unacceptable behaviour
- A procedure for reporting and dealing with unacceptable behaviour

**Comment by annychih** [comment]
Added draft Code of Conduct file here: https://github.com/UBC-MDS/DSCI_522_Group304/blob/master/CODE_OF_CONDUCT.md

Robert and Wenjiao, could you please take a look at it and see if there's anything you'd like changed? Thanks!

**Comment by robilizando** [comment]
I think this look great, we do not need change anything for now
