### ISSUE TITLE
Milestone 1 Release Version?

### ISSUE THREAD

**Issue by robilizando** [UBC-MDS/DSCI_522_Group304#21]
We need to decide on the Number version we want for milestone 1.

Based on the Tutorial I think we have 3 choices:

1) 0.0.1 
2) 0.0.1-0
3) 0.1.0 (Preferred choice I think)

see from the semantic version link: https://semver.org

For 1) above look under the Semantic Versioning Specification (SemVer) section:

4. "Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable."

For 2) above look under the Semantic Versioning Specification (SemVer) section:

9.   ... " Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha"

For 3) above look under the FQA section (1st question):

How should I deal with revisions in the 0.y.z initial development phase?

The simplest thing to do is start your initial development release at 0.1.0 and then increment the minor version for each subsequent release.

**Comment by annychih** [comment]
My vote is for 0.1.0

**Comment by robilizando** [comment]
I vote for 0.1.0 too

**Comment by robilizando** [comment]
I just updated to v0.1.0 and made it a pre-release

**Comment by annychih** [comment]
Sounds good! And thanks, @zouwenjiao for making the initial release!
