### ISSUE TITLE
Milestone 1: CONTRIBUTING file

### ISSUE THREAD

**Issue by annychih** [UBC-MDS/DSCI_522_Group304#3]
Need to make a CONTRIBUTING file and save it to the root of the public GitHub.com project repo

**Comment by annychih** [comment]
Created CONTRIBUTING file. 
@robilizando & @zouwenjiao Please check over it to make sure emails are correct. Thanks!

**Comment by zouwenjiao** [comment]
Thanks Anny! My email address is true.

**Comment by robilizando** [comment]
Email is fine.
