### ISSUE TITLE
Bimodal Distribution for the FSA Writing Score for both Public or Independent School. 

### ISSUE THREAD

**Issue by robilizando** [UBC-MDS/DSCI_522_Group304#49]
The histogram of the FSA Writing Score for both Public or Independent School is showing a bimodal distribution. The mean and confidence intervals look funny when displayed on top of the histograms, but it is what it is. I do not feel we should try to fiddle with. After all we are comparing the mean of the  two groups and both groups show the same type of distribution. 

However, I wanted to raise the issue so we can consult with Tiffany. In case, we feel we want to change something. 

My initial guess is that it has to do with the difference between 4 and 7th grade.

here is the link to the plot:

https://github.com/UBC-MDS/DSCI_522_Group304/blob/master/img/fig_pi_histogram_writing.png

**Comment by annychih** [comment]
I'm pretty sure the bimodal distribution you saw stemmed from the change in the Writing portion of the exam in 2017. I'm closing this issue because we're no longer looking at the Writing portion of the exam.
