### ISSUE TITLE
Bar + Line Plots - Need to Edit Titles and x-axis Name, and x-axis breaks

### ISSUE THREAD

**Issue by annychih** [UBC-MDS/DSCI_522_Group304#53]
Hi @zouwenjiao ! Could you please edit the bar and line graphs so that they follow the same format as the boxplots?

1. The title for the Reading Test bar plot should read "FSA Reading Test Scores (2007/08 - 2018/19)" for example; right now the title has a typo and uses the old format from one of the original EDA code chunks.
2. The x-axis for the bar plots should be "Subgroup" to be consistent with wording throughout the proposal, report etc.
3. The title for the line plots should say something like "FSA Numeracy Test Scores by Subgroup"
4. The y-axis for the line plots should say "Average Score"
5. The x-axis for the line plots should say "School Year Start" (camel case)
6. The x-axis for the line plots need a few more breaks so it's clear what the last year of data is (mark every 1 or 2 years instead of every 3?)
7. The legend for the line plots should say "Subgroup" instead of "sub_population"

Thank you!

**Comment by zouwenjiao** [comment]
OK, I will do that right now.

**Comment by zouwenjiao** [comment]
I have updated the bar and line charts.
