### ISSUE TITLE
References

### ISSUE THREAD

**Issue by annychih** [UBC-MDS/DSCI_522_Group304#55]
I had to remove this source from the ref.bib file for the report.Rmd file to knit. Including it kept throwing an error about an 'unexpected "S"' in the text and I couldn't figure out why it wasn't working. We still need this source in the ref.bib file though. 

Can someone please add this source back into the ref.bib file correctly so that the report.Rmd can knit? @robilizando , can you try to tackle this one?

@online{BC Schools - Foundation Skills Assessment(FSA),
    title = {BC Schools - Foundation Skills Assessment(FSA)},
    author = {Ministry of Education - Education Analytics},
    year = {2019-02-08},
    url = {https://catalogue.data.gov.bc.ca/dataset/bc-schools-foundation-skills-assessment-fsa-},
  }

**Comment by annychih** [comment]
Once this is done, a reference to the exam should be included in the report.Rmd file under the Data section.

**Comment by zouwenjiao** [comment]
I have fixed it.
