### ISSUE TITLE
Writing Exam Change in 2017/2018 - Need Your Input

### ISSUE THREAD

**Issue by annychih** [UBC-MDS/DSCI_522_Group304#56]
While looking into why the line graph for the writing scores showed a steep drop in 2017, I found out that the Writing section of the FSA exam changed that year.

I couldn't find a sample from the old exams, but this article notes that the Writing component WAS out of 12: https://www.fraserinstitute.org/sites/default/files/comparing-the-standardized-test-scores-of-BC-schools.pdf

The current Writing component is now out of 4: https://www2.gov.bc.ca/assets/gov/education/administration/kindergarten-to-grade-12/assessment/fsa_description_specification_june2017.pdf

We have 2 options:
1. Change the dataset so we're only looking at 2007/2008 - 2016/2017 years
2. Only look at Numeracy and Reading portions of the exam

Given that the Writing portion is only one question, I'd like to drop this section from the analysis (option 2). We already have the plots and script made for the full 2007/2008 - 2017/2019 dataset, so by going with Option 2, we just need to change what we reference in the report.

**Comment by robilizando** [comment]
Looks like the problems is beyond just the writing portion of the test. The Numeracy score vs time plots also show the sharp decline. 
I think that the most sensitive thing to do is to drop the data during the cleaning and processing. I do not think we should delete the writing section from the analysis. We should just acknowledge the issue and proposed a solution for next milestone (Perform the analysis over a period of valid data). We are not supposed to solve everything this week . The important thing is what  we have learned so far. 

I think that, our choice of plots helped us determine problems with the data. The most important thing for this class is related to the workflow. The final, occurs in 2 weeks. Your findings so far are good enough.

They can not expect us to solve every thing by milestone 2.

**Comment by annychih** [comment]
Ok, if we go with option 1, we'll need to:
1. edit the clean_data.py script so it takes in only the 2007-2016 data (one argument)
2. re-run everything to get new plots
3. edit the report to include all the Writing plots (they'll be super squished)

@robilizando, after @zouwenjiao comments on this and if option 1 is what we're going to do, could you please do the steps above? Thank you!

**Comment by zouwenjiao** [comment]
I would choose option2. Since we have spent much time on it, it would be easier to just go with numeracy and writing. And I think we should spend more time on other labs now.
@annychih @robilizando
