### ISSUE TITLE
Milestone_3_Project Feedback: make your project even better

### ISSUE THREAD

**Issue by zouwenjiao** [UBC-MDS/DSCI_522_Group304#69]
After the feedback session you will **meet-up** with your partner and **discuss the feedback** you each received and decide how you might move forward improving your project. 

- You should **open an issue or two** to document the feedback you plan to address. Close that issue once you have addressed it.

- In your homework repo on GitHub.ubc.ca, please **provide a link to these (ideally closed) issues** so your TA can easily find them.

**Comment by annychih** [comment]
Here are the links to the 3 sets of peer feedback received in lab:

- https://github.com/UBC-MDS/DSCI_522_Group304/issues/79
- https://github.com/UBC-MDS/DSCI_522_Group304/issues/80
- https://github.com/UBC-MDS/DSCI_522_Group304/issues/78

**Comment by annychih** [comment]
I'm closing this issue since we addressed the peer feedback from the different groups.
