### ISSUE TITLE
Peer Feedback

### ISSUE THREAD

**Issue by camadi** [UBC-MDS/DSCI_522_Group304#79]
- Use tidy for outputs of the model/t-tests
- Encode the values of means/other representations on your plots
- Can you separate gender from your subgroup? This could provide be more insightful as I may want to know how the information for female aboriginal students

- State your null and alternative hypotheses clearly

**Comment by annychih** [comment]
- Added `broom` package and `tidy()` for all t.tests

**Comment by annychih** [comment]
Comment for Item #3: Unfortunately we are not able to separate gender from the Aboriginal / Non Aboriginal subgroups. The dataset doesn't allow for this.

**Comment by annychih** [comment]
Added null and alternative hypotheses statements to the report

**Comment by annychih** [comment]
@robilizando is working on changing item #2

**Comment by robilizando** [comment]
Encode the values of means/other representations on the histograms

**Comment by robilizando** [comment]
We have covered all points relevant to this feedback. So I am closing this issue
