### ISSUE TITLE
Possible Datasets

### ISSUE THREAD

**Issue by annychih** [UBC-MDS/DSCI_522_Group304#8]
We'll need to pick a dataset to work with, so this thread is to add possible datasets for discussion during our team meeting.

**Comment by annychih** [comment]
**Dataset: BC Surgical Wait Times**
**Licence:** Open Government Licence - BC ("free to copy, modify, publish, translate, adapt, distribute, or otherwise use the Information in any medium, mode or format for any lawful purpose.") but must acknowledge the source and provide atribution
**Source:** Ministry of Health - Medical Services
https://catalogue.data.gov.bc.ca/dataset/bc-surgical-wait-times

- Wait time definitions are available here: https://swt.hlth.gov.bc.ca/WaitTimeDefinitions.xhtml
- Pros: dataset has the wait times by hospital and by procedure, and is already very clean
- Cons: It's not stated what units the average wait times are measured in

**Potential Research Questions**
1. Inferential: Are wait times for certain surgeries longer at facilities outside of Vancouver vs within city limits?
2. Inferential: Is there a significant difference in wait times for different hospitals or different procedures?
    - Note: We have about 9 years worth of data x 4 quarters each = 36 possible data points for a given procedure at a hospital. However, the data is by quarter. Can we answer this question using the data we have?
3. Predictive: What is the expected wait time for a procedure at a certain hospital based on median wait times within the same quarter in previous years? The province currently offers wait times based on the past 3 months, but if Christmas holidays are coming up and doctors are taking time off, an estimate based on July-Sep may not be as good as an estimate based on Oct-Dec over the past 9 years.

**Comment by annychih** [comment]
**Dataset: BC Schools - Foundational Skills Assessment (FSA)**
**Licence:** Open Government Licence - BC
**Source:** Ministry of Education - Education Analytics
https://catalogue.data.gov.bc.ca/dataset/bc-schools-foundation-skills-assessment-fsa-

- The field definitions are provided in a PDF file through the link
- Data for 2007-2017 and data for 2017 - 2019 are saved in separate files
- Pros: heaps of data that we can compare by population type (ex. Male / Female / Aboriginal / Non-aboriginal / Special Needs etc), Grade (for the 2007-2017 data), skill type, or school district
- Cons: (can't think of any yet)

**Potential Research Questions**
1. Inferential: How do the scores for certain exams compare between different sub populations (ex. male / female, aboriginal / non-aboriginal, public / private school)? Ex. Do students in private school perform better than students in publicly funded schools on numeracy exams?
    - Null Hypothesis: there's no difference in scores for the different groups
    - Alternative Hypothesis: there is a difference in scores for the different groups

2. Predictive: What score on a specific exam type (ex. numeracy) will a child in a specific sub population (ex. aboriginal) get within a BC publicly funded school based on their:
    - school district, 
    - gender, 
    - how many special needs / non-English language learner are in the school (assuming here that this may influence scores because more funding may be used towards these other groups than to programs that support the aboriginal population specifically), 
    - scores on other exams, and 
    - number of exam writers from the sub population (i.e. number of students within the class that fall within this sub population group)?

3. Predictive: Will the score from Grade 4 influence how they'll perform in Grade 7?

**Comment by zouwenjiao** [comment]
**Dataset: Abalone**
**Source:** UCI Machine Learning Repository
https://www.kaggle.com/rodolfomendes/abalone-dataset

- Predicting the age of abalone from physical measurements.
- Pros: We have fitted regression models for this dataset, so we are familiar with it.
- Cons: Lots of researchers have worked on it, so it is hard to come up with a different research.

**Potential Research Questions**
1. Inferential: How do the average physical features(eg. length, diameter, height, weight) differ between different genders? Ex. Is male abalones' average length significantly different from female's?

2. Predictive: How many rings do a specific abalone have given a set of features:
    - Sex
    - Length
    - Diameter
    - Height
    - Whole weight
    - Shucked weight
    - Viscera weight
    - Shell weight

   (May need feature selection to improve model performance)

**Comment by zouwenjiao** [comment]
**Dataset: Where it pays to attend college**
**Licence:** Other (specified in description)
**Source:** Kaggle
https://www.kaggle.com/wsj/college-salaries

- Salary increase by Type of College, Salaries by Region, Salary increase by Major
- Pros: We can explore the salary in 3 different dimensions and make predictions based on them
- Cons: Miss some important features such as gender to predict salary


**Potential Research Questions**
1. Inferential: How do the average salary differs among different school types? (Ex. Does a graduate from an engineering university get significantly different salary from a graduate from a state university?)

2. Inferential: How do the average salary differs among different regions? (Ex. Does a graduate from a college in LA get significantly different salary from a graduate from a university in NY?)

3. Predictive:  How much salary can a person get given a set of features:
    - Degree
    - Region
    - Major

**Comment by robilizando** [comment]
Dataset: Mining, Quarrying, & Oil & Gas Extraction
Source: DATA USA
https://datausa.io/profile/naics/mining-quarrying-oil-gas-extraction#io

- Know avg salary by year of experience, specific job, etc

**Comment by robilizando** [comment]
Dataset: Data Scientist Job Market in the U.S.
Source: Kaggle
https://www.kaggle.com/sl6149/data-scientist-job-market-in-the-us

- Repeat some of this work. Not all the jobs must have been filled in less than 2 years :)?

Know avg salary by year of experience, specific job, etc

**Comment by annychih** [comment]
Closing this issue because we've decided on a dataset (see Project Proposal issue for more detail): FSA Dataset
