### ISSUE TITLE
Feed back from Frank and George (In lab Peer Review activity)

### ISSUE THREAD

**Issue by robilizando** [UBC-MDS/DSCI_522_Group304#80]
Guys were impressed with the EDA part of the report and how we took the problem from bar charts to box plot, then histogram before making the t-test.  So very compelling argument that there is a significant difference.

They suggested, that parents my be interested in seeing difference between male and females in public vs independent schools system. Apparently, there is another "urban legend" about girls performing much better in private schools than boys due to peer pressure. 

We could explore this if time permits or put it in a recommendation section.

**Comment by annychih** [comment]
That's a very interesting idea and worth exploring in a separate project. However, I wouldn't add it as a recommendation for this project since the scope of our project is strictly to answer our 2 inferential research questions.

**Comment by annychih** [comment]
Since our Milestone 3 feedback included mention that we should include something about future directions, I added a 'Future Direction' section in the report based on this suggestion.
