### ISSUE TITLE
Milestone 2 General Feedback

### ISSUE THREAD

**Issue by yavyx** [UBC-MDS/DSCI_522_Group304#85]
- Excellent report! Question, analysis and conclusions are clear, but missing future directions. Even though you wrote it, make sure you save your figures with the appropriate dimensions to show them properly in the report.
- Remember to write tests/assertions in every function.

**Comment by annychih** [comment]
Thanks for the feedback, Javier!

We've added a section for 'Future Directions' in the report for Milestone 3, and will add test/assertions for all functions for Milestone 4.

**Comment by annychih** [comment]
The team has added tests for all the scripts. Closing issue now :)
