### ISSUE TITLE
Milestone 4 - dependency diagram of the Makefile

### ISSUE THREAD

**Issue by zouwenjiao** [UBC-MDS/DSCI_522_Group304#89]
- Create a dependency diagram of the Makefile using `makefile2graph` and include the image in the README.md file in the root of your project.

**Comment by robilizando** [comment]
Done. We need to see if we like the original size of the image or if we need to change it, to close this issue

**Comment by annychih** [comment]
Since we've checked the size with Firas (a-ok), I'm closing this issue.
