### ISSUE TITLE
Milestone 4 - Make your project reproducible (to the max) with Docker

### ISSUE THREAD

**Issue by zouwenjiao** [UBC-MDS/DSCI_522_Group304#90]
- Write your own Dockerfile (this should include **all the software and libraries/packages** needed to run your analysis pipeline, but not this project itself - i.e., do not git clone your project repo inside your Dockerfile). **This Dockerfile should live in the root of your project repository.**

- Use Docker Hub Automated Build to build your Docker image from your Dockerfile

- Do NOT include any of your data or code in the docker images!

- Include instructions in the project README on how to use your project with and without Docker. I envision that your instructions for using it with Docker should go something like this:

> To run this analysis using Docker, clone/download this repository, use the command line to navigate to the root of this project on your computer, and then type the following (filling in PATH_ON_YOUR_COMPUTER with the absolute path to the root of this project on your computer).

> `docker run --rm -v PATH_ON_YOUR_COMPUTER:/home/data_analysis_eg ttimbers/data_analysis_pipeline_eg make -C '/home/data_analysis_eg' all`

> To clean up the analysis type:

> `docker run --rm -v PATH_ON_YOUR_COMPUTER:/home/data_analysis_eg ttimbers/data_analysis_pipeline_eg make -C '/home/data_analysis_eg' clean`

**Comment by annychih** [comment]
Done! :)

I checked that the Dockerfile ran locally (both after each package was added, and then all together by running the full Dockerfile), then checked that the Docker image was successfully built in DockerHub, and then checked the docker commands that I added to the README. 

All checks passed!
