### ISSUE TITLE
Milestone 4 - Add test for the functions

### ISSUE THREAD

**Issue by zouwenjiao** [UBC-MDS/DSCI_522_Group304#91]
To modify our milestone 2 from TA's feedback, we should write tests for all the functions we use.

**Comment by annychih** [comment]
I added tests for the following scripts:

1. load_data.R
2. clean_data.py
3. add_subgroup_info.py
4. filter_schools_both_subgroups.py
5. plot_publicindep_boxplots.R
6. plot_subgroupsj_boxplots.R

**Comment by zouwenjiao** [comment]
I added tests for the following scripts:

1. data_viz_tab.R
2. plot_publicindep_histogram.R
3. plot_subgroup_histogram.R
