### ISSUE TITLE
Visualization feedback!

### ISSUE THREAD

**Issue by firasm** [UBC-MDS/DSCI_522_Group304#92]
- Wow!! There is some really good and interesting analysis and interpretation here, kudos to your team!
- Below are some thoughts about the visualizations in this report and some suggestions for improvement, and notes when things are done well. You should implement these in milestone4
- - [x] It would really help if you had a caption and a figure/table number for each plot. That way you can easily reference it in your text, and it's easier for readers to find 
- - [x] All figures
	- - [x] Text is quite small, for titles, labels, axes. everything - should increase text size
- - [x] Figure 1:
	- - [x] Overall this is a good choice of plot for what you're trying to show. 
	- - [x] Nice work putting categorical values on the y-axis, makes the plot much more readable!
	- - [x] You have duplicated legends, probably better to reduce whitespace and the redundant legend
	- - [x] You could put the y-axes labels in the middle and have bars going in opposite directions for reading and numeracy (see example [here](http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html#Population%20Pyramid), this will get you most of the way there, you'd probably want to put the y-axis between the plots )
- - [x] Figure 2:
	- - [x] Same arguments about redundant/repeated legends. Can you combine this into a single plot with 4 colours (2 pairs of colours, bright and dim)
	- - [x] Where does your axis start... this is a bit deceiving! Not saying start at 0, but at the very least indicate where it starts.
- - [x] Figure 3:
	- Should you consider a jittered strip plot with the box on top ? See [here](http://www.sthda.com/english/wiki/ggplot2-stripchart-jitter-quick-start-guide-r-software-and-data-visualization) for options. There are a lot of (overplotted) outliers, not clear from the plot how many data points there are
- - [x] Figure 4:
	- - [x] GREAT! This is really good; shows exactly what you want it to. The dotted lines are a bit hard to see and figure out, but once you get it, it's really clear
	- - [x] Consider choosing different colours (the colours in your plot are fine, the annotation colours are different) than red/blue for the annotations and moving the blue annotation to the right side of the plot to further emphasize the point that the independent schools perform significantly better
	- - [x] I would put the legend inside the plot, top right probably!
- - [x] Tables
	- - [x] There is a lot of extraneous information (type of numbers <dbl> for eg) in the tables, you should reformat the table using Kable or KableExtra 
- - [x] Figure 5:
	- - [x] A pyramid plot here would look pretty good too, reading on the right, numeracy on the left
- - [x] Overall the report visualizations are pretty polished, but could use some work with sizing and formatting. Great work! Excellent work with your labels, titles, and plot choices! For every plot I was immediately able to understand what you were trying to convey.

**Comment by annychih** [comment]
For Figure 3: I tried testing out a jitter plot under the boxplot (see image below), but there are so many data points that the only thing it seems to highlight is that there are more public schools than independent schools in the dataset. After considering the pros/cons of the jitter addition, I opted to keep the boxplot as is (without jitter) out of personal preference for a cleaner chart.

![Screen Shot 2020-02-04 at 7 33 15 PM](https://user-images.githubusercontent.com/41139003/73808574-3e51eb80-4785-11ea-9ae9-469015dcaae0.png)

**Comment by annychih** [comment]
For the tables, I used kableExtra and removed everything except the key numbers that tell the story of t-test differences: Estimated Difference, P-value, Lower Confidence Interval, Upper Confidence Interval.

**Comment by annychih** [comment]
Increased text size for boxplots to `base_size = 17`

**Comment by zouwenjiao** [comment]
Modify figure 1, 2, 5, 6

**Comment by annychih** [comment]
Changed boxplot scripts so that they output 1 png file instead of 2. This was done so we can add figure captions the "correct" way.

**Comment by robilizando** [comment]
Modified Histogram as per Firas feedback.

**Comment by annychih** [comment]
Removed boxplots from the report, as per feedback from Firas

**Comment by annychih** [comment]
Figure captions were added for everything

**Comment by annychih** [comment]
I think we've checked off all the boxes, so I'm going to close this issue. Great work, team!

**Comment by firasm** [comment]
Thanks all! Looks good!

Let me know if you felt like you were bullied into removing the boxplot !

**Comment by annychih** [comment]
@firasm Hahaha No!! I was sad about having to delete all the work we put in for the boxplots, but you made a good point about how they're unnecessary. Less is more. Thanks for the feedback!
